###
GET http://localhost/api_back/getuserlist/

###
POST http://localhost/api_back/

{
    "pseudo": "Oliver",
    "password": "passer",
    "action": "login"
}

###
POST http://localhost/api_back/

{
    "pseudo": "Riche",
    "password": "passer",
    "firstname": "Oli",
    "lastname": "Riche",
    "action": "register"
}

###
POST http://localhost/api_back/

{
    "expeditor": 14,
    "receiver": "26",
    "message": "riche",
    "action": "send message"
}

###
GET http://localhost/api_back/getListMessage/2/14
